export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const LOGINFAILEDMODEL = "LOGINFAILEDMODEL";
export const LOGINFALIEDMODELCLOSED = "LOGINFALIEDMODELCLOSED";
export const ADDTOCART = "ADDTOCART";
export const DELETEITEMFROMCART = "DELETEITEMFROMCART";
